routes/web.php
<?php
use App\User;
use Barryvdh\Debugbar;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//debugbar example here
Route::get('/ciao', function () {
    \Debugbar::startMeasure('query_time' ,'The execution time of user query');
    $test = User::get();
    return view('welcome');
    \Debugbar::stopMeasure('query_time');
});
//fullcalender
Route::get('fullcalendar','FullCalendarController@index');
Route::post('fullcalendar/create','FullCalendarController@create');
Route::post('fullcalendar/update','FullCalendarController@update');
Route::post('fullcalendar/delete','FullCalendarController@destroy');

Route::get('/welcome', function () {
    return view('Item.calendar');
});
Route::get('/', function () {
    return redirect('/footballpitch');
    
});
Route::apiResource('/api/pitch', 'Api\PitchController');
Route::apiResource('/api/event', 'Api\EventsController');
Route::apiResource('/api/ticket', 'Api\TicketsController');
Route::apiResource('/api/dashboard', 'Api\DashboardController');
Route::apiResource('/api/review', 'Api\ReviewsController');
Route::get('/api/dashboard/ticket/year', 'Api\DashboardController@Tyear');
Route::get('/api/dashboard/ticket/year/money', 'Api\DashboardController@Pyear');
Route::get('/api/event/calendar/days', 'Api\EventsController@Calendar');
Route::get('/api/ticket/accept/{id}', 'Api\TicketsController@AcceptTicket');
Route::get('/api/ticket/reject/{id}', 'Api\TicketsController@RejectTicket');
Route::get('/api/ticket/ranking/top', 'Api\TicketsController@TopTicket');
Route::get('/api/ticket/user/{id}', 'Api\TicketsController@MyTicket');
Route::get('/api/ticket/user/past/{id}', 'Api\TicketsController@MyOldTicket');
Route::get('/api/pitch/all/ticket/{id}', 'Api\PitchController@TicketBYPitch');
Route::get('/api/review/user/{id}', 'Api\TicketsController@MyReview');
Route::get('/api/pitch/accept/{id}', 'Api\PitchController@AcceptPitch');
Route::get('/api/pitch/reject/{id}', 'Api\PitchController@RejectPitch');
Route::get('/api/pitch/landlord/{id}', 'Api\PitchController@Mypitch');
Route::get('/api/pitch/ranking/top10', 'Api\PitchController@top10ranking');
Route::get('/api/user/ranking/top', 'Api\UserController@TopUser');
//Route::get('/api/pitch/ranking/top20', 'Api\PitchController@ShowOrder');
Route::resource('/review' , 'ReviewController');
Route::resource('/footballpitch' , 'FootballpitchController');
Route::get('/logout' , 'Auth\LoginController@logout')->name('logout');
    Route::get('/review/delete/{id}' , 'ReviewController@delete')->name('review.delete');
    Route::get('/review/update/{id}' , 'ReviewController@update')->name('review.update');
    Route::get('/review/create/{id}' , 'ReviewController@createReview')->name('review.createreview');
    Route::get('/review/edit/{id}' , 'ReviewController@edit')->name('review.edit');
    Route::get('/review/delete/{id}' , 'ReviewController@delete')->name('review.delete');
    Route::resource('/ticket' , 'TicketController');
    Route::resource('/home/event' , 'EventController');
    Route::get('home/settings{id}' ,'HomeController@Setting')->name('home.settings');
    Route::get('/home/acc{id}' , 'HomeController@AcceptTicket')->name('home.accept');
    Route::get('/home/rej{id}' , 'HomeController@RejectTicket')->name('home.reject');
    Route::get('/ticket/create/{id}' , 'TicketController@createTicket')->name('ticket.createticket');
    Route::get('/home', 'HomeController@index')->name('home');
   // Auth::routes();
   Route::post('/login', '\Tuandm\Laravue\Http\Controllers\AuthController@login');
   Route::get('/login', '\Tuandm\Laravue\Http\Controllers\AuthController@laravue');
   //Route::post('/admin/pitch', '\Tuandm\Laravue\Http\Controllers\AuthController@laravue');
   Route::get('/login', function () {
    return redirect('/dashboard');
});
/*Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard' , '\Tuandm\Laravue\Http\Controllers\LaravueController@index');
});*/
//Route::resource('/footballpitch/create/new' , 'AccountController@store');
//Route::resource('/account' , 'AccountController');
/*Route::resource('/ticket' , 'TicketController'){
    $ticket = Ticket::orderBy('date', 'asc')->get();
    return view('task', [
        'task'=> $ticket
    ]);
}*/

//Route::resource('/ticket' , 'TicketController');

//Route::get('/home', 'HomeController@index')->name('home');
//Route::get('/logout' , 'Auth\LoginController@logout')->name('logout');

//Route::resource('/user' , 'UserController');
//Route::resource('/role' , 'RoleController');

/*Route::get('/user', function () {
    return redirect('/setting');
});*/

//Route::resource('/setting' , 'AccountController');
Route::resource('/news', 'NewsController');

Route::resource('/events', 'EventController');

Route::resource('/contacts', 'ContactController');

app/Ticket.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ticket extends Model
{
    protected $fillable = [
        'date',
        'time',
        'import',
        'address',
        'number',
        'account',
        'footballpitch' 
    ];
    public function review()
    {
        return $this->hasOne('App\Review');
    }
}   

app/Http/Controllers/Api/TicketsController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\footballpitch;
use App\Landlord;
use App\Equipment;
use App\Ticket;
use Log;
use App\User;
use Illuminate\Support\Facades\DB;

class TicketsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $ticket = Ticket::all();
        return response()->json($ticket->toArray());
    }   

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'date'=>'required',
            'time'=>'required',
            'import'=>'required',
            'number'=>'required'
        ]);

        $ticket = new Ticket([
            'date' => $request->get('date'),
            'time' => $request->get('time'),
            'import' => $request->get('import'),
            'footballpitch' => $request->get('footballpitch'),
            'account' => $request->get('account'),
            
        ]);
        $ticket->number = $request->get('number');
        $ticket->save();
        return response()->json(['job' => 'success', 'ticket' => 'saved'], 200);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
   public function show($id)
    {
       /* $ticket = Ticket::find($id);
        return  response()->json($ticket->toArray());*/
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $ticket = Ticket::find($id);
        $ticket->date =  $request->get('date');
        $ticket->time = $request->get('time');
        $ticket->import = $request->get('import');
        $ticket->address = $request->get('address');
        $ticket->number = $request->get('number');
        $ticket->save();
        return response()->json(['job' => 'success', 'ticket' => 'updated'], 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $ticket = Ticket::find($id);
        $ticket->delete();
        return response()->json(['job' => 'success', 'ticket' => 'deleted'], 200);
    }
    public function AcceptTicket($id)
    {
        $ticket = Ticket::find($id);
        if(   $ticket->status === 1 )
        {
            $ticket->status = 2 ; //accept
            $ticket->save();
        }
        return response()->json(['job' => 'success', 'ticket' => 'Accepted'], 200);
    }   
    public function RejectTicket($id)
    {
        $ticket = Ticket::find($id);
        if(   $ticket->status === 1 )
        {
            $ticket->status = 3 ; //reject
            $ticket->save();
        }
        return response()->json(['job' => 'success', 'ticket' => 'rejected'], 200);
    } 
    public function TopTicket()
    {   $array = [];
        $tickets = DB::table('tickets')->where( 'status' , '=' , 2 )->orderBy('import' , 'desc')->get();
        array_push( $array , $tickets);
        return response()->json($tickets);
    } 
    public function MyTicket($id)
    {
        $date = date('Y-m-d H:i:s', time());
        log::info($date);
        $ticket = DB::table('tickets')->where([[ 'account' , '=' , $id],['date' ,'>' ,$date],])->get();
        return response()->json($ticket);
    }
    public function MyReview($id)
    {
        $ticket = DB::table('reviews')->where( 'account' , '=' , $id)->get();
        return response()->json($ticket);
    }
    public function MyOldTicket($id)
    {
        $date = date('Y-m-d H:i:s', time());
        log::info($date);
        $ticket = DB::table('tickets')->where([[ 'account' , '=' , $id],['date' ,'<' ,$date],])->get();
        return response()->json($ticket);
    }
}

app/Http/Controllers/TicketController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\footballpitch;
use App\Landlord;
use App\Equipment;
use App\Ticket;
use App\User;
use Auth;
use Log;

class TicketController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
    //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $userId = Auth::id();
        $user = User::find($userId);
        if (Auth::check())
        {
        return view('ticket.create',compact('user'));
        }
        else
        {
        abort('401');
        }
        }

        public function createTicket($id)
        {
            Log::info($id);
            $pitch = footballpitch::find($id);
            $userId = Auth::id();
            $user = User::find($userId);
            $date = date("d/m/Y h:i:s");
            Log::info($user);
            if (Auth::check())
            {
            return view('ticket.create',compact('user','pitch','date'));
            }
            else
            {
            abort('401');
            }
            }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Log::info($request);
        
        $request->validate([
            'date'=>'required',
            'time'=>'required',
            'import'=>'required',
            'number'=>'required'
        ]);

        $ticket = new Ticket([
            'date' => $request->get('date'),
            'time' => $request->get('time'),
            'import' => $request->get('import'),
            'footballpitch' => $request->get('footballpitch'),
            'account' => $request->get('account'),
            
        ]);
        Log::info($ticket);
        $ticket->number = $request->get('number');
        $ticket->save();
        Log::info('ci so');
        return redirect('/home')->with('success', 'Ticket saved!');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (Auth::check())
        {
        Log::info("Show");

        $pitch = footballpitch::find($id);
        $landlord = Landlord::all();
        $equip = Equipment::all();
        $ticket = Ticket::all();

        return view('ticket.show', compact('pitch','landlord','equip','ticket'));}
        else
        {
        abort('401');
        }
        }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit()
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Log::info("Ticket Update");
        /*$request->validate([
            'date'=>'required',
            'time'=>'required',
            'import'=>'required',
            'address'=>'required',
            'number'=>'required'
        ]);*/

        $ticket = Ticket::find($id);
        $ticket->date =  $request->get('date');
        $ticket->time = $request->get('time');
        $ticket->import = $request->get('import');
        $ticket->address = $request->get('address');
        $ticket->number = $request->get('number');
        $ticket->save();

        return redirect('/ticket')->with('success', 'Ticket updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (Auth::check())
        {

        Log::info("Ticket Delete");
        $ticket = Ticket::find($id);
        $ticket->delete();

        return redirect('/ticket')->with('success', 'Ticket deleted!');
        }
        else
            {
            abort('401');
            }
            }
}

resources/views/ticket/create.blade.php
<html>
@extends('layouts.head')
@include('layouts.header')

<body>
   <!--- <h2> Buy a ticket </h2>
    <form method="POST" action="{{ route('ticket.store') }}">
          @csrf
          <div class="form-group">    
              <label for="date">Date:</label>
              <input type="date" class="form-control" name="date"/>
          </div>

          <div class="form-group">
              <label for="time">Time:</label>
              <input type="time" class="form-control" name="time"/>
          </div>

          <div class="form-group">
              <label for="address">Address:</label>
              <input type="text" class="form-control" name="address"/>
          </div>
          <div class="form-group">
              <label for="import">Import:</label>
              <input type="text" class="form-control" name="import"/>
          </div>        
          <div class="form-group">
              <label for="number">Number of people:</label>
              <input type="integer" class="form-control" name="number"/>
          </div>        
          <div>
    <button style="margin: 19px;" type="submit" class="btn btn-primary" >click</button>
    </div> 
          <div>
    <a style="margin: 19px;" href="{{ route('ticket.index')}}" class="btn btn-primary">View list of your tickets</a>
    </div> 
      </form>-->   
      @role('isUser')
    <div class="container">
        <div class="row">
            <h1 class="buyticket-card-title">Submit ticket request to the Landlord</h1>
            <div class="col-7">
                <div class="padding">
                <p class="intro-card-text">Terms and condition.
                        I Termini e le Condizioni d'Uso possono essere adottati per qualsiasi tipologia di sito web o di applicazione, come e-commerce, blog, siti di annunci, siti informativi e di notizie, forum, servizi online, giochi, etc.
                        Per i siti che svolgono attività di e-commerce di beni e/o servizi, e in particolare se l'utente è un "consumatore" (inteso come la persona fisica che agisce per scopi estranei rispetto all’attività imprenditoriale commerciale, artigianale o professionale eventualmente svolta), è obbligatorio fornire specifiche informazioni che riguardano il diritto di recesso (annullamento dell’acquisto), i termini e le modalità per il suo esercizio, la conclusione della vendita, la consegna, etc. (D. Lgs. 206/2005, Codice del Consumo). La violazione degli obblighi informativi può comportare nei confronti del titolare sanzioni che vanno da € 103 a € 10.000. 
                </p>
            </div>
            </div>
            <div class="col-5 ">
                <div class="card card-remind-pitch">
                    <h3 class="card-remind-pitch-title">{{$pitch->name}}</h3>
                    <p>Price at hour : {{$pitch->price_h}} £</p>
                    <p>City: {{$pitch->city}}</p>
                    <p>Address: {{$pitch->address}}</p>
                    <image class="card-remind-pitch-img" src="{{$pitch->image}}"></image>
                </div>
            </div>
            <div class="col-6">
                <div class="card card-ticket">
                    @php
                    $double = $pitch->price_h *2;
                    @endphp
                    <form action="{{route('ticket.store')}}" method="POST">
                        @csrf
                            <div class="form-group">
                                    <label for="number">Number of people:</label>
                                    <input type="integer" class="form-control" name="number" placeholder="For example 22...."/>
                            </div> 

                            <input type="hidden" class="form-control" name="time" value="{{$date}}"/>
                            <input type="hidden" class="form-control" name="footballpitch" value="{{$pitch->id}}"/>
                            <input type="hidden" class="form-control" name="account" value="{{$user->id}}"/>
                             <div class="form-group">
                                    <label for="date">When:</label>
                                    <input type="date" class="form-control" name="date" value=""/>
                            </div> 
                            <div class="form-group">
                                    <label for="hours">How much time:</label>
                                    <select class="form-control" name="import" id="import">
                                            <option value="{{$pitch->price_h}}">1</option>
                                            <option value="{{$double}}">2</option>
                                        </select>
                            </div> 
                            <button class="btn btn-primary" type="submit">Buy</button>
                    </form>
                </div>
            </div>
            <div class="col-6">
                    <div class="card card-payement-method">
                    <div class="form-container">
                    <div class="field-container">
                        <label for="name">Name</label>
                        <input id="name" maxlength="20" type="text">
                    </div>
                    <div class="field-container">
                        <label for="cardnumber">Card Number</label><span id="generatecard">generate random</span>
                        <input id="cardnumber" type="text" pattern="[0-9]*" inputmode="numeric">
                        <svg id="ccicon" class="ccicon" width="750" height="471" viewBox="0 0 750 471" version="1.1" xmlns="http://www.w3.org/2000/svg"
                            xmlns:xlink="http://www.w3.org/1999/xlink">

                        </svg>
                    </div>
                    <div class="field-container">
                        <label for="expirationdate">Expiration (mm/yy)</label>
                        <input id="expirationdate" type="text" pattern="[0-9]*" inputmode="numeric">
                    </div>
                    <div class="field-container">
                        <label for="securitycode">Security Code</label>
                        <input id="securitycode" type="text" pattern="[0-9]*" inputmode="numeric">
                    </div>
                </div>
                    </div>
                </div>
        </div>
    </div>
    @endrole
</body>
@include('layouts.footer')
</html>