routes/web.php
<?php
use App\User;
use Barryvdh\Debugbar;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//debugbar example here
Route::get('/ciao', function () {
    \Debugbar::startMeasure('query_time' ,'The execution time of user query');
    $test = User::get();
    return view('welcome');
    \Debugbar::stopMeasure('query_time');
});
//fullcalender
Route::get('fullcalendar','FullCalendarController@index');
Route::post('fullcalendar/create','FullCalendarController@create');
Route::post('fullcalendar/update','FullCalendarController@update');
Route::post('fullcalendar/delete','FullCalendarController@destroy');

Route::get('/welcome', function () {
    return view('Item.calendar');
});
Route::get('/', function () {
    return redirect('/footballpitch');
    
});
Route::apiResource('/api/pitch', 'Api\PitchController');
Route::apiResource('/api/event', 'Api\EventsController');
Route::apiResource('/api/ticket', 'Api\TicketsController');
Route::apiResource('/api/dashboard', 'Api\DashboardController');
Route::apiResource('/api/review', 'Api\ReviewsController');
Route::get('/api/dashboard/ticket/year', 'Api\DashboardController@Tyear');
Route::get('/api/dashboard/ticket/year/money', 'Api\DashboardController@Pyear');
Route::get('/api/event/calendar/days', 'Api\EventsController@Calendar');
Route::get('/api/ticket/accept/{id}', 'Api\TicketsController@AcceptTicket');
Route::get('/api/ticket/reject/{id}', 'Api\TicketsController@RejectTicket');
Route::get('/api/ticket/ranking/top', 'Api\TicketsController@TopTicket');
Route::get('/api/ticket/user/{id}', 'Api\TicketsController@MyTicket');
Route::get('/api/ticket/user/past/{id}', 'Api\TicketsController@MyOldTicket');
Route::get('/api/pitch/all/ticket/{id}', 'Api\PitchController@TicketBYPitch');
Route::get('/api/review/user/{id}', 'Api\TicketsController@MyReview');
Route::get('/api/pitch/accept/{id}', 'Api\PitchController@AcceptPitch');
Route::get('/api/pitch/reject/{id}', 'Api\PitchController@RejectPitch');
Route::get('/api/pitch/landlord/{id}', 'Api\PitchController@Mypitch');
Route::get('/api/pitch/ranking/top10', 'Api\PitchController@top10ranking');
Route::get('/api/user/ranking/top', 'Api\UserController@TopUser');
//Route::get('/api/pitch/ranking/top20', 'Api\PitchController@ShowOrder');
Route::resource('/review' , 'ReviewController');
Route::resource('/footballpitch' , 'FootballpitchController');
Route::get('/logout' , 'Auth\LoginController@logout')->name('logout');
    Route::get('/review/delete/{id}' , 'ReviewController@delete')->name('review.delete');
    Route::get('/review/update/{id}' , 'ReviewController@update')->name('review.update');
    Route::get('/review/create/{id}' , 'ReviewController@createReview')->name('review.createreview');
    Route::get('/review/edit/{id}' , 'ReviewController@edit')->name('review.edit');
    Route::get('/review/delete/{id}' , 'ReviewController@delete')->name('review.delete');
    Route::resource('/ticket' , 'TicketController');
    Route::resource('/home/event' , 'EventController');
    Route::get('home/settings{id}' ,'HomeController@Setting')->name('home.settings');
    Route::get('/home/acc{id}' , 'HomeController@AcceptTicket')->name('home.accept');
    Route::get('/home/rej{id}' , 'HomeController@RejectTicket')->name('home.reject');
    Route::get('/ticket/create/{id}' , 'TicketController@createTicket')->name('ticket.createticket');
    Route::get('/home', 'HomeController@index')->name('home');
   // Auth::routes();
   Route::post('/login', '\Tuandm\Laravue\Http\Controllers\AuthController@login');
   Route::get('/login', '\Tuandm\Laravue\Http\Controllers\AuthController@laravue');
   //Route::post('/admin/pitch', '\Tuandm\Laravue\Http\Controllers\AuthController@laravue');
   Route::get('/login', function () {
    return redirect('/dashboard');
});
/*Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard' , '\Tuandm\Laravue\Http\Controllers\LaravueController@index');
});*/
//Route::resource('/footballpitch/create/new' , 'AccountController@store');
//Route::resource('/account' , 'AccountController');
/*Route::resource('/ticket' , 'TicketController'){
    $ticket = Ticket::orderBy('date', 'asc')->get();
    return view('task', [
        'task'=> $ticket
    ]);
}*/

//Route::resource('/ticket' , 'TicketController');

//Route::get('/home', 'HomeController@index')->name('home');
//Route::get('/logout' , 'Auth\LoginController@logout')->name('logout');

//Route::resource('/user' , 'UserController');
//Route::resource('/role' , 'RoleController');

/*Route::get('/user', function () {
    return redirect('/setting');
});*/

//Route::resource('/setting' , 'AccountController');
Route::resource('/news', 'NewsController');

Route::resource('/events', 'EventController');

Route::resource('/contacts', 'ContactController');

app/Event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    protected $fillable = [
        'title',
        'image',
        'start',
        'end',
        'footballpitch_id',
        'description'
    ];
    public function footballpitch()
    {
        return $this->belongsTo('App\footballpitch');
    }
}

app/Http/Controllers/Api/EventsController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Event;
use Log;
use Illuminate\Support\Facades\DB;


class EventsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $event = Event::all();
        return response()->json($event->toArray());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title'=>'required',
            'image'=>'required',
            'start'=>'required',
            'end'=>'required',
            'description'=>'required'
        ]); 

        $event = new Event([
            'title' => $request->get('title'),
            'image' => $request->get('image'),
            'start' => $request->get('start'),
            'end' => $request->get('end'),
            'description' => $request->get('description'),
            'footballpitch_id'  => $request->get('footballpitch_id')
        ]);
        $event->save();

        return response()->json(['job' => 'success', 'event' => 'saved'], 200);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       
       /* $event = Event::find($id);
        return response()->json($event->toArray());*/
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $event = Event::find($id);
        $event->title =  $request->get('title');
        $event->image = $request->get('image');
        $event->footballpitch_id = $request->get('footballpitch_id');
        $event->start = $request->get('start');
        $event->end = $request->get('end');
        $event->description = $request->get('description');
        $event->save();

        return response()->json(['job' => 'success', 'Event' => 'updated'], 200);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $event = Event::find($id);
        $event->delete();
        return response()->json(['job' => 'success'], 200);
    }

    public function Calendar()
    {
        $event = DB::table('events')->get();
        return response()->json($event);
    }
}  

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\footballpitch;
use App\Event;
use Auth;

use Log;

class EventController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        Log::info("Event index");

        $events = Event::all();

        return view('events.index', compact('events'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $id_user = Auth::user()->id;
        $pitch = footballpitch::all()->where('landlord',$id_user);
        Log::info("Event create");

        return view('events.create', compact('pitch'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Log::info("Event store");


        $request->validate([
            'title'=>'required',
            'image'=>'required',
            'start'=>'required',
            'end'=>'required',
            'description'=>'required'
        ]); 

        $event = new Event([
            'title' => $request->get('title'),
            'image' => $request->get('image'),
            'start' => $request->get('start'),
            'end' => $request->get('end'),
            'description' => $request->get('description'),
            'footballpitch_id'  => $request->get('footballpitch_id')
        ]);
        $event->save();

        Log::info($event);
        return redirect('/events')->with('success', 'Event saved!');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        Log::info("Event edit");

        $event = Event::find($id);
        return view('events.edit', compact('event')); 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $pitch = footballpitch::all();
        Log::info("Event update");

      /*  $request->validate([
            'title'=>'required',
            'image'=>'required',
            'type_of_event'=>'required',
            'date'=>'required',
            'description'=>'required'
        ]); */

        $event = Event::find($id);
        $event->title =  $request->get('title');
        $event->image = $request->get('image');
        $event->footballpitch_id = $request->get('footballpitch_id');
        $event->start = $request->get('start');
        $event->end = $request->get('end');
        $event->description = $request->get('description');
        $event->save();

        return redirect('/events')->with('success', 'Event updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Log::info("Event destroy");

        $event = Event::find($id);
        $event->delete();

        return redirect('/home')->with('success', 'Event deleted!');
    }
}

resources/views/events/create.blade.php
@extends('layouts.head')
@include('layouts.header')

<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Add an event</h1>
      <form method="post" action="{{ route('events.store') }}">
          @csrf
          <div class="form-group">    
              <label for="title">Title:</label>
              <input type="text" class="form-control" name="title"/>
          </div>

          <div class="form-group">
              <label for="image">Image:</label>
              <input type="text" class="form-control" name="image"/>
          </div>

          <div class="form-group">
              <label for="type_of_event">Date start:</label>
              <input type="date" class="form-control" name="start"/>
          </div>
          <div class="form-group">
              <label for="date">Date end:</label>
              <input type="date" class="form-control" name="end"/>
          </div>
          <div class="form-group">
              <label for="type_of_event"> Football pitch:</label>
              <select class="form-control" name="footballpitch_id" id="footballpitch_id">
                  @foreach($pitch as $camp)
                    <option value="{{$camp->id}}"> {{$camp->name}}</option>
                  @endforeach
              </select>
          </div>
          <div class="form-group">
              <label for="description">Decription:</label>
              <input type="text" class="form-control" name="description"/>
          </div>                         
          <button type="submit" class="btn btn-primary-outline">Add an event</button>
      </form>
  </div>
</div>
</div>
@include('layouts.footer')

resources/views/events/edit.blade.php
@extends('layouts.head')
@include('layouts.header')
<div class="container">
<div class="row">
    <div class="col-6">
        <h1 class="display-3">Update an event</h1>
        <form method="post" action="{{ route('events.update', $event->id) }}">
            @method('PATCH') 
            @csrf
            <div class="form-group">

                <label for="title">Title:</label>
                <input type="text" class="form-control" name="title" value={{ $event->title }} />
            </div>

            <div class="form-group">
                <label for="image">Image:</label>
                <input type="text" class="form-control" name="image" value={{ $event->image }} />
            </div>

            <div class="form-group">
                <label for="type_of_event">Date start:</label>
                <input type="text" class="form-control" name="type_of_event" value={{ $event->start }} />
            </div>
            <div class="form-group">
                <label for="date">Date end:</label>
                <input type="date" class="form-control" name="date" value={{ $event->end }} />
            </div>
            <div class="form-group">
                <label for="description">description:</label>
                <input type="text" class="form-control" name="description" value={{ $event->description }} />
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
    <div class="col-6">
        <form action="{{route('event.destroy', $event->id)}}" method="post">
            @method('DELETE')
            @csrf
            <button class="btn btn-danger" type="submit">U can Delete too</button>
        </form>
    </div>
</div>
</div>
@include('layouts.footer')

resources/views/events/index.blade.php
@extends('base')
@section('main')
<html>
    <head>
        <h1> Show all events </h1>
        <a style="margin: 19px;" href="{{ route('events.create')}}" class="btn btn-primary">Return</a>

    </head>
    <div>
    <a style="margin: 19px;" href="{{ route('events.create')}}" class="btn btn-primary">New event</a>
    </div>  
    <div class="col-sm-12">
@section('main')
<div class="row">
<div class="col-sm-12">
    <h1 class="display-3">Event</h1>    
  <table class="table table-striped">
    <thead>
        <tr>
          <td>Title</td>
          <td>Image</td>
          <td>Type of event</td>
          <td>Date</td>
          <td>Description</td>
          <td colspan = 2>Actions</td>
        </tr>
    </thead>  <tbody>
        @foreach($events as $event)
        <tr>
            <td>{{$event->title}}</td>
            <td>{{$event->image}}</td>
            <td>{{$event->type_of_event}}</td>
            <td>{{$event->date}}</td>
            <td>{{$event->description}}</td>
            <td>
                <a href="{{ route('events.edit',$event->id)}}" class="btn btn-primary">Edit</a>
            </td>
            <td>
                <form action="{{ route('events.destroy', $event->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>  
  </table>
<div>
</div>
@endsection


  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>
</html>