routes/web.php
<?php
use App\User;
use Barryvdh\Debugbar;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//debugbar example here
Route::get('/ciao', function () {
    \Debugbar::startMeasure('query_time' ,'The execution time of user query');
    $test = User::get();
    return view('welcome');
    \Debugbar::stopMeasure('query_time');
});
//fullcalender
Route::get('fullcalendar','FullCalendarController@index');
Route::post('fullcalendar/create','FullCalendarController@create');
Route::post('fullcalendar/update','FullCalendarController@update');
Route::post('fullcalendar/delete','FullCalendarController@destroy');

Route::get('/welcome', function () {
    return view('Item.calendar');
});
Route::get('/', function () {
    return redirect('/footballpitch');
    
});
Route::apiResource('/api/pitch', 'Api\PitchController');
Route::apiResource('/api/event', 'Api\EventsController');
Route::apiResource('/api/ticket', 'Api\TicketsController');
Route::apiResource('/api/dashboard', 'Api\DashboardController');
Route::apiResource('/api/review', 'Api\ReviewsController');
Route::get('/api/dashboard/ticket/year', 'Api\DashboardController@Tyear');
Route::get('/api/dashboard/ticket/year/money', 'Api\DashboardController@Pyear');
Route::get('/api/event/calendar/days', 'Api\EventsController@Calendar');
Route::get('/api/ticket/accept/{id}', 'Api\TicketsController@AcceptTicket');
Route::get('/api/ticket/reject/{id}', 'Api\TicketsController@RejectTicket');
Route::get('/api/ticket/ranking/top', 'Api\TicketsController@TopTicket');
Route::get('/api/ticket/user/{id}', 'Api\TicketsController@MyTicket');
Route::get('/api/ticket/user/past/{id}', 'Api\TicketsController@MyOldTicket');
Route::get('/api/pitch/all/ticket/{id}', 'Api\PitchController@TicketBYPitch');
Route::get('/api/review/user/{id}', 'Api\TicketsController@MyReview');
Route::get('/api/pitch/accept/{id}', 'Api\PitchController@AcceptPitch');
Route::get('/api/pitch/reject/{id}', 'Api\PitchController@RejectPitch');
Route::get('/api/pitch/landlord/{id}', 'Api\PitchController@Mypitch');
Route::get('/api/pitch/ranking/top10', 'Api\PitchController@top10ranking');
Route::get('/api/user/ranking/top', 'Api\UserController@TopUser');
//Route::get('/api/pitch/ranking/top20', 'Api\PitchController@ShowOrder');
Route::resource('/review' , 'ReviewController');
Route::resource('/footballpitch' , 'FootballpitchController');
Route::get('/logout' , 'Auth\LoginController@logout')->name('logout');
    Route::get('/review/delete/{id}' , 'ReviewController@delete')->name('review.delete');
    Route::get('/review/update/{id}' , 'ReviewController@update')->name('review.update');
    Route::get('/review/create/{id}' , 'ReviewController@createReview')->name('review.createreview');
    Route::get('/review/edit/{id}' , 'ReviewController@edit')->name('review.edit');
    Route::get('/review/delete/{id}' , 'ReviewController@delete')->name('review.delete');
    Route::resource('/ticket' , 'TicketController');
    Route::resource('/home/event' , 'EventController');
    Route::get('home/settings{id}' ,'HomeController@Setting')->name('home.settings');
    Route::get('/home/acc{id}' , 'HomeController@AcceptTicket')->name('home.accept');
    Route::get('/home/rej{id}' , 'HomeController@RejectTicket')->name('home.reject');
    Route::get('/ticket/create/{id}' , 'TicketController@createTicket')->name('ticket.createticket');
    Route::get('/home', 'HomeController@index')->name('home');
   // Auth::routes();
   Route::post('/login', '\Tuandm\Laravue\Http\Controllers\AuthController@login');
   Route::get('/login', '\Tuandm\Laravue\Http\Controllers\AuthController@laravue');
   //Route::post('/admin/pitch', '\Tuandm\Laravue\Http\Controllers\AuthController@laravue');
   Route::get('/login', function () {
    return redirect('/dashboard');
});
/*Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard' , '\Tuandm\Laravue\Http\Controllers\LaravueController@index');
});*/
//Route::resource('/footballpitch/create/new' , 'AccountController@store');
//Route::resource('/account' , 'AccountController');
/*Route::resource('/ticket' , 'TicketController'){
    $ticket = Ticket::orderBy('date', 'asc')->get();
    return view('task', [
        'task'=> $ticket
    ]);
}*/

//Route::resource('/ticket' , 'TicketController');

//Route::get('/home', 'HomeController@index')->name('home');
//Route::get('/logout' , 'Auth\LoginController@logout')->name('logout');

//Route::resource('/user' , 'UserController');
//Route::resource('/role' , 'RoleController');

/*Route::get('/user', function () {
    return redirect('/setting');
});*/

//Route::resource('/setting' , 'AccountController');
Route::resource('/news', 'NewsController');

Route::resource('/events', 'EventController');

Route::resource('/contacts', 'ContactController');

app/Http/Controllers/Api/ReviewsController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Review;


class ReviewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $review = Review::find($id);
        return response()->json($review);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/ReviewController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\footballpitch;
use App\Equipment;
use App\Ticket;
use App\Review;
use App\User;
use Log;
use Illuminate\Support\Facades\DB;
use Auth;

class ReviewController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function createReview($id)
    {
        $userId = Auth::id();
        $users = User::all();
        $footballpitch = footballpitch::all();
        $user = User::find($userId);
        $pitch = DB::table('tickets')->where('id' , $id)->first();
        $reviews = DB::table('reviews')->where('footballpitch' , $pitch->footballpitch)->orderBy('created_at' , 'asc' )->get();
        if (Auth::check())
        {
            log::info('create');
            return view('review.create',compact('user','id','pitch','reviews','users','footballpitch'));
        }
        else
        {
            log::info('401');
        abort('401');
        }
        }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Log::info("Review Store");

        $review = new Review([
            'star' => $request->get('star'),
            'comment' => $request->get('comment'),
            'ticket' => $request->get('ticket'),
            'review' => $request->get('review'),
            'account' => $request->get('account'),
            'footballpitch' => $request->get('footballpitch')
            
        ]);
        Log::info($review);
        $review->save();
        return redirect('/home')->with('success', 'Review saved!');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        log::info('qui');
        $userId = Auth::id();
        $users = User::all();
        $footballpitch = footballpitch::all();
        $user = User::find($userId);
        $pitch = DB::table('tickets')->where('id' , $id)->first();
        $reviews = DB::table('reviews')
        ->join('tickets', 'reviews.ticket' ,'=','tickets.id')
        ->where('reviews.ticket', $id)
        ->get();
        $revi = Review::find($id);
        
        return view('review.edit', compact('reviews','footballpitch','user','pitch','users','id','revi'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Log::info($request);
        $request->validate([
            'star'=>'required',
            'account'=>'required',
            'footballpitch'=>'required'
        ]);
        Log::info($request);
        $review = Review::find($id);
        $review->star =  $request->get('star');
        $review->account = $request->get('account');
        $review->footballpitch = $request->get('footballpitch');
        $review->comment =  $request->get('comment');
        $review->ticket =  $request->get('ticket');
        $review->update();

        return redirect('/home')->with('success', 'Review updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Log::info("Review Delete");
        $review = Review::find($id);
        $review->delete();

        return redirect('/review')->with('success', 'Review deleted!');
    }
    public function delete($id)
    {
        $review = Review::find($id);
        $review->delete();

        return redirect('/home')->with('success', 'Review deleted!');
    }
}

resources/views/review/create.blade.php
<html>
@extends('layouts.head')

    @include('layouts.header')
<body>
    <div class="container">
        <div class="row">
             <div class="container">
                 <!--Review like a chat-->
                 @foreach($footballpitch as $foot)
                    @if($foot->id === $pitch->footballpitch)
                    <h1 class="review-title">Review {{$foot->name}}</h1>
                  
                <div class="card-reviews" style="background: url({{$foot->image}});background-repeat: no-repeat;">
                        @endif
                        @endforeach
                    @foreach($reviews as $revie)
                        @if($revie->account == $user->id)
                            <div class=" card-your-review ">
                                <image class="avatar-chat" src="{{$user->image}}"></image>
                                <h3>You</h3>
                                <div>
                                    @for($i=0; $i < $revie->star; $i++)
                                    <span class="fa fa-star checked"></span>
                                    @endfor
                                    @for($i=5; $i > $revie->star; $i --)
                                    <span class="fa fa-star"></span>
                                    @endfor
                                </div>
                                <p>{{$revie->comment}}</p>

                                <p><small><i class="fa fa-check" aria-hidden="true"></i>{{$revie->created_at}}</small></p>
                            </div>
                        @else
                            <div class="card card-somebody-review">
                                @foreach($users as $boi)
                                    @if($boi->id === $revie->account)
                                    <image class="avatar-chat" src="{{$boi->image}}"></image>
                                    <h3>{{$boi->name}} {{$boi->surname}}</h3>
                                    @endif
                                @endforeach
                                <div>
                                        @for($i=0; $i<$revie->star; $i++)
                                        <span class="fa fa-star checked"></span>
                                        @endfor
                                        @for($i=5; $i>$revie->star; $i --)
                                        <span class="fa fa-star"></span>
                                        @endfor
                                </div>
                                    <p>{{$revie->comment}}</p>
                                <p><small><i class="fa fa-check" aria-hidden="true"></i>{{$revie->created_at}}</small></p>
                            </div>
                        @endif
                    @endforeach
                </div>
            </div>
            <div class="card write-comment-card">
                <form action="{{route('review.store')}}" method="post" >
                    @csrf
                    
                    <div class="form-group">
                            <label>Your review:</label>
                            <input type="text" class="form-control" name="comment" placeholder="write here ..."/>
                    </div>

                    <div class="form-group">
                        <input type="hidden" class="form-control" name="account" value="{{$user->id}}"/>
                    </div>

                    <div class="form-group">
                        <input type="hidden" class="form-control" name="ticket" value="{{$id}}"/>
                    </div>

                    <div class="form-group">
                        <input type="hidden" class="form-control" name="footballpitch" value="{{$pitch->footballpitch}}">
                    </div>

                    <div class="rate">
                            <input type="radio" id="star5" name="star" value="5" />
                            <label for="star5" title="5">5 stars</label>
                            <input type="radio" id="star4" name="star" value="4" />
                            <label for="star4" title="4">4 stars</label>
                            <input type="radio" id="star3" name="star" value="3" />
                            <label for="star3" title="3">3 stars</label>
                            <input type="radio" id="star2" name="star" value="2" />
                            <label for="star2" title="2">2 stars</label>
                            <input type="radio" id="star1" name="star" value="1" />
                            <label for="star1" title="1">1 star</label>
                    </div>
                        <button  type="submit" class="btn btn-primary" >Send</button>
                </form>
        </div>
        </div>
    </div>
</body>
@include('layouts.footer')
</html>

resources/views/review/edit.blade.php
<html>
@extends('layouts.head')

    @include('layouts.header')
<body>
    <div class="container">
        <div class="row">
             <div class="container">
                 <!--Review like a chat-->
                 @foreach($footballpitch as $foot)
                    @if($foot->id === $pitch->footballpitch)
                    <h1 class="review-title">Edit your review {{$foot->name}}</h1>
                <div  class="card-reviews" style="background: url({{$foot->image}});background-repeat: no-repeat;">
                        @endif
                        @endforeach
                    @foreach($reviews as $revie)
                        @if($revie->account == $user->id)
                            <div class=" card-your-review ">
                                <image class="avatar-chat" src="{{$user->image}}"></image>
                                <h3>You</h3>
                                <div>
                                    @for($i=0; $i < $revie->star; $i++)
                                    <span class="fa fa-star checked"></span>
                                    @endfor
                                    @for($i=5; $i > $revie->star; $i --)
                                    <span class="fa fa-star"></span>
                                    @endfor
                                </div>
                                <p>{{$revie->comment}}</p>

                                <p><small><i class="fa fa-check" aria-hidden="true"></i>{{$revie->created_at}}</small></p>
                            </div>
                        @else
                            <div class="card card-somebody-review">
                                @foreach($users as $boi)
                                    @if($boi->id === $revie->account)
                                    <image class="avatar-chat" src="{{$boi->image}}"></image>
                                    <h3>{{$boi->name}} {{$boi->surname}}</h3>
                                    @endif
                                @endforeach
                                <div>
                                        @for($i=0; $i<$revie->star; $i++)
                                        <span class="fa fa-star checked"></span>
                                        @endfor
                                        @for($i=5; $i>$revie->star; $i --)
                                        <span class="fa fa-star"></span>
                                        @endfor
                                </div>
                                    <p>{{$revie->comment}}</p>
                                <p><small><i class="fa fa-check" aria-hidden="true"></i>{{$revie->created_at}}</small></p>
                            </div>
                        @endif
                    @endforeach
                </div>
            </div>
            <div class="card write-comment-card">
                <form action="{{route('review.update', $revi->id)}}" method="put" >
                    @csrf
                    <div class="form-group">
                            <label>Your review:</label>
                            <input type="text" class="form-control" name="comment" value="{{$revi->comment}}"/>
                    </div>

                    <div class="form-group">
                        <input type="hidden" class="form-control" name="account" value="{{$revi->account}}"/>
                    </div>

                    <div class="form-group">
                        <input type="hidden" class="form-control" name="ticket" value="{{$revi->ticket}}"/>
                    </div>

                    <div class="form-group">
                        <input type="hidden" class="form-control" name="footballpitch" value="{{$revi->footballpitch}}">
                    </div>

                    <div class="rate">
                            <input type="radio" id="star5" name="star" value="5" />
                            <label for="star5" title="5">5 stars</label>
                            <input type="radio" id="star4" name="star" value="4" />
                            <label for="star4" title="4">4 stars</label>
                            <input type="radio" id="star3" name="star" value="3" />
                            <label for="star3" title="3">3 stars</label>
                            <input type="radio" id="star2" name="star" value="2" />
                            <label for="star2" title="2">2 stars</label>
                            <input type="radio" id="star1" name="star" value="1" />
                            <label for="star1" title="1">1 star</label>
                    </div>
                        <button  type="submit" class="btn btn-primary" >Modify</button>
                </form>
        </div>
        </div>
    </div>
</body>
@include('layouts.footer')
</html>

resources/views/review/index.blade.php
@extends('base')
@section('main')
<html>
    <head>
        <h1> Show all yours tickets </h1>
        <a style="margin: 19px;" href="{{ route('review.create')}}" class="btn btn-primary">Return</a>

    </head>
    <div>
    <a style="margin: 19px;" href="{{ route('review.create')}}" class="btn btn-primary">New review</a>
    </div>  
    <div class="col-sm-12">
@section('main')
<div class="row">
<div class="col-sm-12">
    <h1 class="display-3">Review</h1>    
  <table class="table table-striped">
    <thead>
        <tr>
          <td>Star</td>
          <td>Review</td>
     <!--     <td>Account</td>
          <td>Footballpitch</td> -->
          <td colspan = 2>Actions</td>
        </tr>
    </thead>  <tbody>
        @foreach($review as $review)
        <tr>
            <td>{{$review->star}}</td>
            <td>{{$review->review}}</td>
          <!--  <td>{{$review->account}}</td>
            <td>{{$review->footballpitch}}</td> */ -->
            <td>
                <a href="{{ route('review.edit',$review->id)}}" class="btn btn-primary">Edit</a>
            </td>
            <td>
                <form action="{{ route('review.destroy', $review->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>  
  </table>
<div>
</div>
@endsection


  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>
</html>

resources/views/review/show.blade.php
<html>
@extends('layouts.head')

    @include('layouts.header')
   <body>     
    @section('main')
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <div class="card card-user">
                    <h1> Your Reviews:</h1>
                   <h3>Star: {{$review->star}}</h3>
                   <h3>Review:{{$review->review}}</h3>
                <!--   <h3>Account: {{$review->account}}</h3>
                   <h3>Footballpitch {{$review->footballpitch}}</h3>  -->
                    
            </div>
                </div>
                @can('Create a pitch')
                <div class="col-6">
                        
                    <a href="{{route('review.create')}}">Create new review</a>
                       
                </div>
                @endcan
            </div>
            <div class="container">
                <div class="row">
                    <div>
                        
                    </div>
                </div>
            </div>
        </div>
        @include('layouts.footer')
    </body>
    </html>