routes/web.php
<?php
use App\User;
use Barryvdh\Debugbar;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//debugbar example here
Route::get('/ciao', function () {
    \Debugbar::startMeasure('query_time' ,'The execution time of user query');
    $test = User::get();
    return view('welcome');
    \Debugbar::stopMeasure('query_time');
});
//fullcalender
Route::get('fullcalendar','FullCalendarController@index');
Route::post('fullcalendar/create','FullCalendarController@create');
Route::post('fullcalendar/update','FullCalendarController@update');
Route::post('fullcalendar/delete','FullCalendarController@destroy');

Route::get('/welcome', function () {
    return view('Item.calendar');
});
Route::get('/', function () {
    return redirect('/footballpitch');
    
});
Route::apiResource('/api/pitch', 'Api\PitchController');
Route::apiResource('/api/event', 'Api\EventsController');
Route::apiResource('/api/ticket', 'Api\TicketsController');
Route::apiResource('/api/dashboard', 'Api\DashboardController');
Route::apiResource('/api/review', 'Api\ReviewsController');
Route::get('/api/dashboard/ticket/year', 'Api\DashboardController@Tyear');
Route::get('/api/dashboard/ticket/year/money', 'Api\DashboardController@Pyear');
Route::get('/api/event/calendar/days', 'Api\EventsController@Calendar');
Route::get('/api/ticket/accept/{id}', 'Api\TicketsController@AcceptTicket');
Route::get('/api/ticket/reject/{id}', 'Api\TicketsController@RejectTicket');
Route::get('/api/ticket/ranking/top', 'Api\TicketsController@TopTicket');
Route::get('/api/ticket/user/{id}', 'Api\TicketsController@MyTicket');
Route::get('/api/ticket/user/past/{id}', 'Api\TicketsController@MyOldTicket');
Route::get('/api/pitch/all/ticket/{id}', 'Api\PitchController@TicketBYPitch');
Route::get('/api/review/user/{id}', 'Api\TicketsController@MyReview');
Route::get('/api/pitch/accept/{id}', 'Api\PitchController@AcceptPitch');
Route::get('/api/pitch/reject/{id}', 'Api\PitchController@RejectPitch');
Route::get('/api/pitch/landlord/{id}', 'Api\PitchController@Mypitch');
Route::get('/api/pitch/ranking/top10', 'Api\PitchController@top10ranking');
Route::get('/api/user/ranking/top', 'Api\UserController@TopUser');
//Route::get('/api/pitch/ranking/top20', 'Api\PitchController@ShowOrder');
Route::resource('/review' , 'ReviewController');
Route::resource('/footballpitch' , 'FootballpitchController');
Route::get('/logout' , 'Auth\LoginController@logout')->name('logout');
    Route::get('/review/delete/{id}' , 'ReviewController@delete')->name('review.delete');
    Route::get('/review/update/{id}' , 'ReviewController@update')->name('review.update');
    Route::get('/review/create/{id}' , 'ReviewController@createReview')->name('review.createreview');
    Route::get('/review/edit/{id}' , 'ReviewController@edit')->name('review.edit');
    Route::get('/review/delete/{id}' , 'ReviewController@delete')->name('review.delete');
    Route::resource('/ticket' , 'TicketController');
    Route::resource('/home/event' , 'EventController');
    Route::get('home/settings{id}' ,'HomeController@Setting')->name('home.settings');
    Route::get('/home/acc{id}' , 'HomeController@AcceptTicket')->name('home.accept');
    Route::get('/home/rej{id}' , 'HomeController@RejectTicket')->name('home.reject');
    Route::get('/ticket/create/{id}' , 'TicketController@createTicket')->name('ticket.createticket');
    Route::get('/home', 'HomeController@index')->name('home');
   // Auth::routes();
   Route::post('/login', '\Tuandm\Laravue\Http\Controllers\AuthController@login');
   Route::get('/login', '\Tuandm\Laravue\Http\Controllers\AuthController@laravue');
   //Route::post('/admin/pitch', '\Tuandm\Laravue\Http\Controllers\AuthController@laravue');
   Route::get('/login', function () {
    return redirect('/dashboard');
});
/*Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard' , '\Tuandm\Laravue\Http\Controllers\LaravueController@index');
});*/
//Route::resource('/footballpitch/create/new' , 'AccountController@store');
//Route::resource('/account' , 'AccountController');
/*Route::resource('/ticket' , 'TicketController'){
    $ticket = Ticket::orderBy('date', 'asc')->get();
    return view('task', [
        'task'=> $ticket
    ]);
}*/

//Route::resource('/ticket' , 'TicketController');

//Route::get('/home', 'HomeController@index')->name('home');
//Route::get('/logout' , 'Auth\LoginController@logout')->name('logout');

//Route::resource('/user' , 'UserController');
//Route::resource('/role' , 'RoleController');

/*Route::get('/user', function () {
    return redirect('/setting');
});*/

//Route::resource('/setting' , 'AccountController');
Route::resource('/news', 'NewsController');

Route::resource('/events', 'EventController');

Route::resource('/contacts', 'ContactController');

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    protected $fillable = [
        'title',
        'image',
        'author',
        'url',
        'date',
        'description'
    ];
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\News;
use Log;

class NewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        Log::info("News index");

        $news = News::all();

        return view('news.index', compact('news'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        Log::info("News create");

        return view('news.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        log::info("News store");
        
        $request->validate([
            'title'=>'required',
            'image'=>'required',
            'type_of_news'=>'required',
            'date'=>'required',
            'description'=>'required'
        ]);

        $news = new News([
            'title' => $request->get('title'),
            'image' => $request->get('image'),
            'type_of_news' => $request->get('type_of_news'),
            'date' => $request->get('date'),
            'description' => $request->get('description')
        ]);
        $news->save();
        return redirect('/news')->with('success', 'News saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        Log::info("News edit");

        $news = News::find($id);
        return view('news.edit', compact('news'));   
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Log::info("News update");

        $request->validate([
            'title'=>'required',
            'image'=>'required',
            'type_of_news'=>'required',
            'date'=>'required',
            'description'=>'required'
        ]);

        $news = News::find($id);
        $news->title =  $request->get('title');
        $news->image = $request->get('image');
        $news->type_of_news = $request->get('type_of_news');
        $news->date = $request->get('date');
        $news->description = $request->get('description');
        $news->save();

        return redirect('/news')->with('success', 'News updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Log::info("News destroy");

        $news = News::find($id);
        $news->delete();

        return redirect('/news')->with('success', 'News deleted!');
    }
}

resources/views/news/create.blade.php
@extends('base')

@section('main')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Add a news</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('news.store') }}">
          @csrf
          <div class="form-group">    
              <label for="title">Title:</label>
              <input type="text" class="form-control" name="title"/>
          </div>

          <div class="form-group">
              <label for="image">Image:</label>
              <input type="text" class="form-control" name="image"/>
          </div>

          <div class="form-group">
              <label for="type_of_news">Type of news:</label>
              <input type="text" class="form-control" name="type_of_news"/>
          </div>
          <div class="form-group">
              <label for="date">Date:</label>
              <input type="date" class="form-control" name="date"/>
          </div>
          <div class="form-group">
              <label for="description">Description:</label>
              <input type="text" class="form-control" name="description"/>
          </div>                  
          <button type="submit" class="btn btn-primary-outline">Add news</button>
      </form>
  </div>
</div>
</div>
@endsection

resources/views/news/edit.blade.php
@extends('base') 
@section('main')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Update a news</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('news.update', $news->id) }}">
            @method('PATCH') 
            @csrf
            <div class="form-group">

                <label for="title">Title:</label>
                <input type="text" class="form-control" name="title" value={{ $news->title }} />
            </div>

            <div class="form-group">
                <label for="image">Image:</label>
                <input type="text" class="form-control" name="image" value={{ $news->image }} />
            </div>

            <div class="form-group">
                <label for="type-of_news">Type of news:</label>
                <input type="text" class="form-control" name="type_of_news" value={{ $news->type_of_news }} />
            </div>
            <div class="form-group">
                <label for="date">Date:</label>
                <input type="date" class="form-control" name="date" value={{ $news->date }} />
            </div>
            <div class="form-group">
                <label for="description">Description:</label>
                <input type="text" class="form-control" name="description" value={{ $news->description }} />
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>
@endsection

resources/views/news/index.blade.php
@extends('base')
@section('main')
<html>
    <head>
        <h1> Show News </h1>
        <a style="margin: 19px;" href="{{ route('news.create')}}" class="btn btn-primary">Return</a>

        <div>
    <a style="margin: 19px;" href="{{ route('news.create')}}" class="btn btn-primary">New ticket</a>
    </div>  
    </head>
    <div class="col-sm-12">
@section('main')
<div class="row">
<div class="col-sm-12">
    <h1 class="display-3">News</h1>    
  <table class="table table-striped">
    <thead>
        <tr>
          <td>Title</td>
          <td>Image</td>
          <td>Type of news</td>
          <td>Date</td>
          <td>Description</td>
          <td colspan = 2>Actions</td>
        </tr>
    </thead>  <tbody>
        @foreach($news as $new)
        <tr>
            <td>{{$new->title}}</td>
            <td>{{$new->image}}</td>
            <td>{{$new->type_of_news}}</td>
            <td>{{$new->date}}</td>
            <td>{{$new->description}}</td>
            <td>
                <a href="{{ route('news.edit',$new->id)}}" class="btn btn-primary">Edit</a>
            </td>
            <td>
                <form action="{{ route('news.destroy', $new->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>  
  </table>
<div>
</div>
@endsection


  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>
</html>